title: Hongmei Kang's Homepage
page-top-title: Hongmei Kang
top-section-bg-text: Computer Science
home-subtitle: Hongmei Kang&ensp;|&ensp;康红梅
copyright-text: '&copy; Hongmei Kang 2023-2025. All Rights Reserved.'
